INSERT INTO industries_master
(
name, 
rephrased_name, 
slug, 
initial, 
seo_title, 
seo_description, 
image_Path, 
icon, 
color, 
description, 
market_size, 
growth_rate, 
top_players, 
market_size_value, 
growth_rate_value, 
overview, 
priority, 
isActive, 
ip, 
createAt, 
createBY
)
VALUES
-- 1️⃣ Healthcare (P1)
(
  'Healthcare',
  'Healthcare Market Research',
  'healthcare',
  'HC',
  'Healthcare Market Size, Share & Growth Report',
  'Healthcare market research covering pharmaceuticals, medical devices, biotechnology, and healthcare services with market size, trends, and forecast.',
  '/images/industries/healthcare.webp',
  'stethoscope',
  '#1976D2',
  'Pharma, biotech, medical devices and healthcare services',
  'USD 10+ Tn',
  '7.5%',
  'Pfizer, Roche, Johnson & Johnson',
  10000000000000,
  7.5,
  'Healthcare is the highest-demand industry for market research due to regulatory requirements, continuous innovation, aging populations, and high investment activity across pharmaceuticals, medical devices, and healthcare services.',
  1,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 2️⃣ ICT (P2)
(
  'Information & Communications Technology',
  'ICT Market Research',
  'information-communications-technology',
  'ICT',
  'ICT Market Size, Trends & Forecast Report',
  'ICT market research covering software, AI, cloud computing, cybersecurity, and telecom infrastructure.',
  '/images/industries/ict.webp',
  'cpu',
  '#3949AB',
  'Software, AI, cloud, cybersecurity and telecom',
  'USD 5+ Tn',
  '9.0%',
  'Microsoft, Google, IBM',
  5000000000000,
  9.0,
  'The ICT industry is driven by rapid digital transformation, enterprise software adoption, cloud computing, artificial intelligence, and cybersecurity needs.',
  2,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 3️⃣ Energy & Power (P3)
(
  'Energy & Power',
  'Energy and Power Market Research',
  'energy-power',
  'EP',
  'Energy and Power Market Size & Growth Outlook',
  'Energy and power market research covering renewable energy, utilities, energy storage, and oil & gas.',
  '/images/industries/energy.webp',
  'zap',
  '#F9A825',
  'Renewable energy, utilities, storage, oil and gas',
  'USD 2+ Tn',
  '6.8%',
  'Siemens Energy, GE, NextEra',
  2000000000000,
  6.8,
  'Energy and power markets are driven by sustainability goals, government policies, and long-term infrastructure investments.',
  3,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 4️⃣ Semiconductor & Electronics (P4)
(
  'Semiconductor & Electronics',
  'Semiconductor Market Research',
  'semiconductor-electronics',
  'SE',
  'Semiconductor and Electronics Market Forecast',
  'Semiconductor and electronics market research covering chips, components, and electronic systems.',
  '/images/industries/semiconductor.webp',
  'cpu',
  '#5E35B1',
  'Semiconductors, chips, electronics and components',
  'USD 600+ Bn',
  '8.5%',
  'Intel, TSMC, Samsung',
  600000000000,
  8.5,
  'The semiconductor and electronics industry is capital intensive and strategically critical, with strong demand driven by supply chain sensitivity and rapid technological change.',
  4,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 5️⃣ Automotive & Transportation (P5)
(
  'Automotive & Transportation',
  'Automotive Market Research',
  'automotive-transportation',
  'AT',
  'Automotive and Transportation Market Trends & Forecast',
  'Automotive market research covering vehicles, EVs, batteries, mobility services, and logistics.',
  '/images/industries/automotive.webp',
  'car',
  '#546E7A',
  'Vehicles, EVs, batteries, mobility and logistics',
  'USD 3+ Tn',
  '8.0%',
  'Toyota, Tesla, Volkswagen',
  3000000000000,
  8.0,
  'Automotive and transportation markets are undergoing rapid transformation due to electric vehicles, autonomous driving, and smart mobility solutions.',
  5,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 6️⃣ Chemicals & Materials (P6)
(
  'Chemicals & Materials',
  'Chemicals Market Research',
  'chemicals-materials',
  'CM',
  'Chemicals and Materials Market Size & Outlook',
  'Chemicals and materials market research covering specialty chemicals, polymers, and industrial materials.',
  '/images/industries/chemicals.webp',
  'flask',
  '#00897B',
  'Specialty chemicals, polymers and materials',
  'USD 4+ Tn',
  '5.5%',
  'BASF, Dow, SABIC',
  4000000000000,
  5.5,
  'The chemicals and materials industry supports multiple end-use sectors and requires market research for capacity planning, compliance, and innovation strategy.',
  6,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 7️⃣ Consumer Goods & FMCG (P7)
(
  'Consumer Goods & FMCG',
  'Consumer Goods and FMCG Market Research',
  'consumer-goods-fmcg',
  'FMC',
  'Consumer Goods and FMCG Market Analysis',
  'Consumer goods and FMCG market research covering personal care, household products, and fast-moving consumer goods.',
  '/images/industries/fmcg.webp',
  'shopping-bag',
  '#6D4C41',
  'Fast-moving consumer goods, personal care and household products',
  'USD 11+ Tn',
  '5.1%',
  'Unilever, P&G, Nestle',
  11000000000000,
  5.1,
  'The consumer goods and FMCG industry focuses on high-volume products and depends heavily on consumer behavior, branding, pricing, and product innovation.',
  7,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 8️⃣ Food & Beverage (P8)
(
  'Food & Beverage',
  'Food and Beverage Market Research',
  'food-beverage',
  'FB',
  'Food and Beverage Market Size & Trends',
  'Food and beverage market research covering processed foods, beverages, ingredients, and nutrition trends.',
  '/images/industries/food.webp',
  'shopping-bag',
  '#6D4C41',
  'Processed food, beverages and ingredients',
  'USD 8+ Tn',
  '5.0%',
  'Nestle, PepsiCo, Unilever',
  8000000000000,
  5.0,
  'Food and beverage companies rely on market research to understand consumer trends, product launches, pricing strategies, and regulatory compliance.',
  8,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 9️⃣ Agriculture & Food (P9)
(
  'Agriculture & Food',
  'Agriculture and Food Market Research',
  'agriculture-food',
  'AGF',
  'Agriculture and Food Market Outlook',
  'Agriculture and food market research covering agri-tech, fertilizers, crop protection, and food processing.',
  '/images/industries/agriculture.webp',
  'leaf',
  '#2E7D32',
  'Agriculture, agri-tech, fertilizers, food processing',
  'USD 5+ Tn',
  '6.3%',
  'Bayer, Syngenta, Corteva',
  5000000000000,
  6.3,
  'The agriculture and food industry is driven by population growth, food security concerns, and increasing adoption of agri-tech solutions.',
  9,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 🔟 BFSI (P10)
(
  'BFSI',
  'BFSI Market Research',
  'bfsi',
  'BF',
  'BFSI Market Size, Digital Banking & Fintech Trends',
  'BFSI market research covering banking, insurance, financial services, fintech, and payments.',
  '/images/industries/bfsi.webp',
  'bank',
  '#283593',
  'Banking, financial services, insurance and fintech',
  'USD 20+ Tn',
  '6.2%',
  'JPMorgan, Visa, Mastercard',
  20000000000000,
  6.2,
  'The BFSI industry depends on market intelligence for regulatory compliance, digital banking transformation, fintech innovation, and risk management.',
  10,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
),

-- 1️⃣1️⃣ Aerospace & Defense (P11)
(
  'Aerospace & Defense',
  'Aerospace and Defense Market Research',
  'aerospace-defense',
  'AD',
  'Aerospace and Defense Market Forecast',
  'Aerospace and defense market research covering aircraft, defense systems, UAVs, and space technologies.',
  '/images/industries/aerospace.webp',
  'plane',
  '#455A64',
  'Aircraft, defense systems, UAVs and space',
  'USD 900+ Bn',
  '4.8%',
  'Lockheed Martin, Boeing',
  900000000000,
  4.8,
  'Aerospace and defense markets are driven by government spending, national security priorities, and long-term contracts.',
  11,
  b'1',
  '127.0.0.1',
  CURRENT_TIMESTAMP,
  1
);
