--------------------------------------------------
-- Industry : Healthcare --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Pharmaceuticals (P1)
(
  1,
  'Pharmaceuticals',
  'Pharmaceutical Market Research',
  'pharmaceuticals',
  'PHAR',
  'Pharmaceutical Market Size, Share & Forecast',
  'Pharmaceutical market research covering drugs, therapeutics, generics, and branded medicines with market size and forecast.',
  '/images/sub-industries/pharmaceuticals.webp',
  'pill',
  '#1976D2',
  'Prescription drugs, generics and branded medicines',
  'USD 1.6 Trillion',
  '6.5%',
  'Pfizer, Novartis, Roche',
  1600000000000,
  6.5,
  'The pharmaceutical industry forms the backbone of global healthcare, driven by chronic diseases, innovation in therapeutics, and increasing healthcare expenditure worldwide.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Medical Devices (P2)
(
  1,
  'Medical Devices',
  'Medical Devices Market Research',
  'medical-devices',
  'MD',
  'Medical Devices Market Size & Growth Outlook',
  'Medical devices market research covering diagnostic equipment, surgical instruments, and healthcare devices.',
  '/images/sub-industries/medical-devices.webp',
  'activity',
  '#1565C0',
  'Diagnostic, surgical and therapeutic medical devices',
  'USD 600 Billion',
  '7.2%',
  'Medtronic, GE Healthcare, Siemens Healthineers',
  600000000000,
  7.2,
  'Medical devices play a critical role in diagnosis, treatment, and patient monitoring, with strong growth driven by technological innovation and aging populations.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Biotechnology (P3)
(
  1,
  'Biotechnology',
  'Biotechnology Market Research',
  'biotechnology',
  'BIO',
  'Biotechnology Market Trends & Forecast',
  'Biotechnology market research covering biologics, biosimilars, gene therapy, and cell therapy.',
  '/images/sub-industries/biotechnology.webp',
  'dna',
  '#6A1B9A',
  'Biologics, biosimilars and advanced therapies',
  'USD 1.3 Trillion',
  '9.8%',
  'Amgen, Gilead, Biogen',
  1300000000000,
  9.8,
  'The biotechnology industry is transforming healthcare through advanced therapies, biologics, and precision medicine, supported by strong R&D investments.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Diagnostics (P4)
(
  1,
  'Diagnostics',
  'Diagnostics Market Research',
  'diagnostics',
  'DIAG',
  'Diagnostics Market Size & Growth Analysis',
  'Diagnostics market research covering in-vitro diagnostics, imaging, and point-of-care testing.',
  '/images/sub-industries/diagnostics.webp',
  'microscope',
  '#00838F',
  'In-vitro diagnostics, imaging and testing services',
  'USD 110 Billion',
  '6.9%',
  'Roche Diagnostics, Abbott, Siemens Healthineers',
  110000000000,
  6.9,
  'Diagnostics enable early disease detection and clinical decision-making, making them a key growth segment in global healthcare.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Digital Health (P5)
(
  1,
  'Digital Health',
  'Digital Health Market Research',
  'digital-health',
  'DH',
  'Digital Health Market Size, Trends & Forecast',
  'Digital health market research covering telemedicine, health IT, AI in healthcare, and remote patient monitoring.',
  '/images/sub-industries/digital-health.webp',
  'monitor',
  '#2E7D32',
  'Telemedicine, health IT, AI and remote monitoring',
  'USD 350 Billion',
  '18.5%',
  'Teladoc, Cerner, Epic Systems',
  350000000000,
  18.5,
  'Digital health is rapidly reshaping healthcare delivery through telemedicine, AI-powered diagnostics, and connected health solutions.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Hospitals & Healthcare Services (P6)
(
  1,
  'Hospitals & Healthcare Services',
  'Healthcare Services Market Research',
  'healthcare-services',
  'HCS',
  'Healthcare Services Market Size & Outlook',
  'Healthcare services market research covering hospitals, clinics, and patient care services.',
  '/images/sub-industries/healthcare-services.webp',
  'hospital',
  '#455A64',
  'Hospitals, clinics and patient care services',
  'USD 9.5 Trillion',
  '5.4%',
  'HCA Healthcare, Mayo Clinic, Apollo Hospitals',
  9500000000000,
  5.4,
  'Healthcare services represent the largest share of healthcare spending globally, driven by population growth and rising chronic disease prevalence.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Vaccines (P7)
(
  1,
  'Vaccines',
  'Vaccines Market Research',
  'vaccines',
  'VAC',
  'Vaccines Market Size, Share & Forecast',
  'Vaccines market research covering preventive and therapeutic vaccines.',
  '/images/sub-industries/vaccines.webp',
  'syringe',
  '#8E24AA',
  'Preventive and therapeutic vaccines',
  'USD 75 Billion',
  '8.6%',
  'GSK, Sanofi, Moderna',
  75000000000,
  8.6,
  'The vaccines market is driven by immunization programs, emerging infectious diseases, and increasing focus on preventive healthcare.',
  7,
  b'1',
  '127.0.0.1',
  1
);


--------------------------------------------------
-- Industry : Healthcare --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Software & SaaS (P1)
(
  2,
  'Software & SaaS',
  'Software and SaaS Market Research',
  'software-saas',
  'SaaS',
  'Software and SaaS Market Size, Trends & Forecast',
  'Software and SaaS market research covering enterprise software, SaaS platforms, and application services.',
  '/images/sub-industries/software.webp',
  'code',
  '#3949AB',
  'Enterprise software, SaaS platforms and applications',
  'USD 900 Billion',
  '11.2%',
  'Microsoft, Oracle, Salesforce',
  900000000000,
  11.2,
  'The software and SaaS market forms the backbone of digital transformation, driven by cloud adoption, subscription models, and enterprise automation.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Cloud Computing (P2)
(
  2,
  'Cloud Computing',
  'Cloud Computing Market Research',
  'cloud-computing',
  'CLOUD',
  'Cloud Computing Market Size & Growth Outlook',
  'Cloud computing market research covering public, private, and hybrid cloud services.',
  '/images/sub-industries/cloud.webp',
  'cloud',
  '#1E88E5',
  'Public, private and hybrid cloud services',
  'USD 600 Billion',
  '14.5%',
  'Amazon Web Services, Microsoft Azure, Google Cloud',
  600000000000,
  14.5,
  'Cloud computing enables scalable IT infrastructure and digital agility, making it one of the fastest-growing ICT sub-industries.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Artificial Intelligence (P3)
(
  2,
  'Artificial Intelligence',
  'Artificial Intelligence Market Research',
  'artificial-intelligence',
  'AI',
  'Artificial Intelligence Market Size, Share & Forecast',
  'Artificial intelligence market research covering machine learning, deep learning, and AI-driven applications.',
  '/images/sub-industries/ai.webp',
  'cpu',
  '#6A1B9A',
  'AI, machine learning and intelligent systems',
  'USD 500 Billion',
  '20.1%',
  'Google, NVIDIA, OpenAI',
  500000000000,
  20.1,
  'Artificial intelligence is transforming industries through automation, predictive analytics, and intelligent decision-making.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Cybersecurity (P4)
(
  2,
  'Cybersecurity',
  'Cybersecurity Market Research',
  'cybersecurity',
  'CYBER',
  'Cybersecurity Market Size & Threat Landscape',
  'Cybersecurity market research covering network security, endpoint protection, and data security.',
  '/images/sub-industries/cybersecurity.webp',
  'shield',
  '#D32F2F',
  'Network, endpoint and data security solutions',
  'USD 250 Billion',
  '12.8%',
  'Palo Alto Networks, CrowdStrike, Fortinet',
  250000000000,
  12.8,
  'Cybersecurity demand continues to rise due to increasing cyber threats, regulatory requirements, and cloud adoption.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Big Data & Analytics (P5)
(
  2,
  'Big Data & Analytics',
  'Big Data and Analytics Market Research',
  'big-data-analytics',
  'BDA',
  'Big Data and Analytics Market Trends & Forecast',
  'Big data and analytics market research covering data platforms, analytics tools, and business intelligence.',
  '/images/sub-industries/big-data.webp',
  'database',
  '#00897B',
  'Data analytics, business intelligence and platforms',
  'USD 350 Billion',
  '13.4%',
  'IBM, SAP, SAS',
  350000000000,
  13.4,
  'Big data and analytics enable organizations to derive actionable insights from structured and unstructured data.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Internet of Things (IoT) (P6)
(
  2,
  'Internet of Things (IoT)',
  'IoT Market Research',
  'internet-of-things',
  'IOT',
  'Internet of Things Market Size & Outlook',
  'IoT market research covering connected devices, platforms, and industrial IoT.',
  '/images/sub-industries/iot.webp',
  'wifi',
  '#5D4037',
  'Connected devices, platforms and IoT solutions',
  'USD 650 Billion',
  '10.9%',
  'Cisco, Siemens, Bosch',
  650000000000,
  10.9,
  'The Internet of Things connects physical devices to digital systems, enabling automation, monitoring, and smart infrastructure.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Telecom & Networking (P7)
(
  2,
  'Telecom & Networking',
  'Telecom and Networking Market Research',
  'telecom-networking',
  'TEL',
  'Telecom and Networking Market Size & Forecast',
  'Telecom and networking market research covering 5G, broadband, and communication infrastructure.',
  '/images/sub-industries/telecom.webp',
  'signal',
  '#455A64',
  'Telecommunications, networking and 5G infrastructure',
  'USD 1.7 Trillion',
  '5.2%',
  'AT&T, Verizon, Huawei',
  1700000000000,
  5.2,
  'Telecom and networking infrastructure remains essential for global connectivity and digital services.',
  7,
  b'1',
  '127.0.0.1',
  1
);


--------------------------------------------------
-- Industry : Energy & Power --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Oil & Gas (P1)
(
  3,
  'Oil & Gas',
  'Oil and Gas Market Research',
  'oil-gas',
  'OIL',
  'Oil and Gas Market Size, Trends & Forecast',
  'Oil and gas market research covering upstream, midstream, downstream, and energy services.',
  '/images/sub-industries/oil-gas.webp',
  'droplet',
  '#455A64',
  'Upstream, midstream and downstream oil & gas',
  'USD 6.5 Trillion',
  '4.5%',
  'Saudi Aramco, ExxonMobil, Shell',
  6500000000000,
  4.5,
  'The oil and gas industry remains a major contributor to global energy supply, driven by industrial demand, transportation needs, and energy security concerns.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Renewable Energy (P2)
(
  3,
  'Renewable Energy',
  'Renewable Energy Market Research',
  'renewable-energy',
  'REN',
  'Renewable Energy Market Size & Growth Outlook',
  'Renewable energy market research covering solar, wind, hydro, and renewable power generation.',
  '/images/sub-industries/renewable-energy.webp',
  'sun',
  '#2E7D32',
  'Solar, wind, hydro and renewable power',
  'USD 1.5 Trillion',
  '9.6%',
  'NextEra Energy, Vestas, Siemens Gamesa',
  1500000000000,
  9.6,
  'Renewable energy is rapidly expanding due to decarbonization goals, government incentives, and declining technology costs.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Power Generation & Utilities (P3)
(
  3,
  'Power Generation & Utilities',
  'Power Generation Market Research',
  'power-generation',
  'PWR',
  'Power Generation and Utilities Market Forecast',
  'Power generation market research covering utilities, power plants, and electricity generation.',
  '/images/sub-industries/power-generation.webp',
  'zap',
  '#F9A825',
  'Electricity generation, utilities and grids',
  'USD 2.8 Trillion',
  '5.3%',
  'EDF, Duke Energy, NTPC',
  2800000000000,
  5.3,
  'Power generation and utilities form the backbone of energy infrastructure, supporting industrial, commercial, and residential electricity demand.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Energy Storage (P4)
(
  3,
  'Energy Storage',
  'Energy Storage Market Research',
  'energy-storage',
  'ES',
  'Energy Storage Market Size, Trends & Forecast',
  'Energy storage market research covering batteries, grid storage, and energy storage systems.',
  '/images/sub-industries/energy-storage.webp',
  'battery',
  '#1565C0',
  'Battery storage and grid energy storage systems',
  'USD 400 Billion',
  '18.2%',
  'Tesla Energy, LG Energy Solution, Fluence',
  400000000000,
  18.2,
  'Energy storage enables grid stability, renewable integration, and efficient power management, making it a critical growth segment.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Hydrogen Energy (P5)
(
  3,
  'Hydrogen Energy',
  'Hydrogen Energy Market Research',
  'hydrogen-energy',
  'H2',
  'Hydrogen Energy Market Size & Outlook',
  'Hydrogen energy market research covering green hydrogen, blue hydrogen, and hydrogen infrastructure.',
  '/images/sub-industries/hydrogen.webp',
  'flame',
  '#00838F',
  'Green, blue hydrogen and hydrogen infrastructure',
  'USD 300 Billion',
  '22.5%',
  'Air Liquide, Linde, Plug Power',
  300000000000,
  22.5,
  'Hydrogen energy is emerging as a key decarbonization solution for heavy industry, transportation, and power generation.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Smart Grid & Transmission (P6)
(
  3,
  'Smart Grid & Transmission',
  'Smart Grid Market Research',
  'smart-grid',
  'GRID',
  'Smart Grid Market Size & Forecast',
  'Smart grid market research covering transmission, distribution, and grid modernization technologies.',
  '/images/sub-industries/smart-grid.webp',
  'network',
  '#3949AB',
  'Power transmission, distribution and smart grids',
  'USD 500 Billion',
  '8.1%',
  'Siemens, ABB, Schneider Electric',
  500000000000,
  8.1,
  'Smart grid technologies enhance grid efficiency, reliability, and integration of renewable energy sources.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Nuclear Energy (P7)
(
  3,
  'Nuclear Energy',
  'Nuclear Energy Market Research',
  'nuclear-energy',
  'NUC',
  'Nuclear Energy Market Size & Outlook',
  'Nuclear energy market research covering nuclear power plants, fuel, and reactors.',
  '/images/sub-industries/nuclear.webp',
  'radioactive',
  '#6D4C41',
  'Nuclear power plants and nuclear fuel',
  'USD 450 Billion',
  '3.8%',
  'Rosatom, EDF, Westinghouse',
  450000000000,
  3.8,
  'Nuclear energy provides stable baseload power and is regaining attention as a low-carbon energy source.',
  7,
  b'1',
  '127.0.0.1',
  1
);


--------------------------------------------------
-- Industry : Semiconductor & Electronics --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Semiconductors (P1)
(
  4,
  'Semiconductors',
  'Semiconductor Market Research',
  'semiconductors',
  'SEMI',
  'Semiconductor Market Size, Share & Forecast',
  'Semiconductor market research covering integrated circuits, logic chips, memory, and fabrication technologies.',
  '/images/sub-industries/semiconductors.webp',
  'cpu',
  '#5E35B1',
  'Integrated circuits, logic, memory and chips',
  'USD 600 Billion',
  '8.5%',
  'TSMC, Intel, Samsung',
  600000000000,
  8.5,
  'The semiconductor industry is the foundation of modern electronics, driven by demand from computing, automotive, industrial, and consumer applications.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Consumer Electronics (P2)
(
  4,
  'Consumer Electronics',
  'Consumer Electronics Market Research',
  'consumer-electronics',
  'CE',
  'Consumer Electronics Market Size & Trends',
  'Consumer electronics market research covering smartphones, wearables, TVs, and personal devices.',
  '/images/sub-industries/consumer-electronics.webp',
  'smartphone',
  '#3949AB',
  'Smartphones, wearables and consumer devices',
  'USD 1.1 Trillion',
  '6.2%',
  'Apple, Samsung, Sony',
  1100000000000,
  6.2,
  'Consumer electronics demand is driven by innovation cycles, rising disposable income, and increasing adoption of smart devices.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Electronic Components (P3)
(
  4,
  'Electronic Components',
  'Electronic Components Market Research',
  'electronic-components',
  'EC',
  'Electronic Components Market Size & Outlook',
  'Electronic components market research covering passive and active electronic components.',
  '/images/sub-industries/electronic-components.webp',
  'chip',
  '#00897B',
  'Capacitors, resistors, sensors and connectors',
  'USD 550 Billion',
  '7.1%',
  'Murata, TDK, TE Connectivity',
  550000000000,
  7.1,
  'Electronic components are essential building blocks for electronics manufacturing across automotive, industrial, and consumer sectors.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Embedded Systems (P4)
(
  4,
  'Embedded Systems',
  'Embedded Systems Market Research',
  'embedded-systems',
  'EMB',
  'Embedded Systems Market Size & Forecast',
  'Embedded systems market research covering hardware, firmware, and real-time operating systems.',
  '/images/sub-industries/embedded.webp',
  'settings',
  '#455A64',
  'Embedded hardware, firmware and RTOS',
  'USD 110 Billion',
  '9.4%',
  'NXP, Renesas, Microchip',
  110000000000,
  9.4,
  'Embedded systems enable intelligent control and automation across industrial, automotive, and consumer applications.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Displays & Optoelectronics (P5)
(
  4,
  'Displays & Optoelectronics',
  'Display and Optoelectronics Market Research',
  'displays-optoelectronics',
  'DISP',
  'Displays and Optoelectronics Market Trends',
  'Displays and optoelectronics market research covering LEDs, OLEDs, LCDs, and optical components.',
  '/images/sub-industries/displays.webp',
  'monitor',
  '#1E88E5',
  'LED, OLED, LCD and optical components',
  'USD 180 Billion',
  '6.8%',
  'Samsung Display, LG Display, BOE',
  180000000000,
  6.8,
  'Displays and optoelectronics technologies support visual interfaces and lighting solutions across consumer and industrial markets.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Sensors & MEMS (P6)
(
  4,
  'Sensors & MEMS',
  'Sensors and MEMS Market Research',
  'sensors-mems',
  'MEMS',
  'Sensors and MEMS Market Size & Growth',
  'Sensors and MEMS market research covering motion sensors, pressure sensors, and micro-electromechanical systems.',
  '/images/sub-industries/sensors.webp',
  'radar',
  '#6A1B9A',
  'Motion, pressure and MEMS sensors',
  'USD 140 Billion',
  '10.3%',
  'Bosch, STMicroelectronics, Analog Devices',
  140000000000,
  10.3,
  'Sensors and MEMS are critical for smart devices, automotive systems, and industrial automation.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Power Electronics (P7)
(
  4,
  'Power Electronics',
  'Power Electronics Market Research',
  'power-electronics',
  'PWR',
  'Power Electronics Market Size & Outlook',
  'Power electronics market research covering power semiconductors, converters, and inverters.',
  '/images/sub-industries/power-electronics.webp',
  'zap',
  '#F9A825',
  'Power semiconductors, converters and inverters',
  'USD 90 Billion',
  '8.9%',
  'Infineon, ON Semiconductor, Wolfspeed',
  90000000000,
  8.9,
  'Power electronics enable efficient energy conversion and are essential for EVs, renewable energy, and industrial power systems.',
  7,
  b'1',
  '127.0.0.1',
  1
);



--------------------------------------------------
-- Industry : Automotive & Transportation --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Electric Vehicles (P1)
(
  5,
  'Electric Vehicles',
  'Electric Vehicles Market Research',
  'electric-vehicles',
  'EV',
  'Electric Vehicles Market Size, Share & Forecast',
  'Electric vehicles market research covering passenger EVs, commercial EVs, and electric mobility.',
  '/images/sub-industries/electric-vehicles.webp',
  'car',
  '#2E7D32',
  'Passenger and commercial electric vehicles',
  'USD 550 Billion',
  '18.2%',
  'Tesla, BYD, Volkswagen',
  550000000000,
  18.2,
  'The electric vehicles market is rapidly expanding due to emission regulations, battery cost reduction, and growing adoption of clean mobility solutions.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Automotive Components (P2)
(
  5,
  'Automotive Components',
  'Automotive Components Market Research',
  'automotive-components',
  'COMP',
  'Automotive Components Market Size & Outlook',
  'Automotive components market research covering engine parts, drivetrain, braking, and chassis systems.',
  '/images/sub-industries/automotive-components.webp',
  'settings',
  '#455A64',
  'Engine parts, drivetrain, braking and chassis',
  'USD 2.1 Trillion',
  '6.4%',
  'Bosch, Denso, Magna',
  2100000000000,
  6.4,
  'Automotive components form the backbone of vehicle manufacturing, with demand driven by vehicle production and technological advancements.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Automotive Electronics (P3)
(
  5,
  'Automotive Electronics',
  'Automotive Electronics Market Research',
  'automotive-electronics',
  'AE',
  'Automotive Electronics Market Size & Forecast',
  'Automotive electronics market research covering ADAS, infotainment, sensors, and electronic control units.',
  '/images/sub-industries/automotive-electronics.webp',
  'cpu',
  '#3949AB',
  'ADAS, infotainment, sensors and ECUs',
  'USD 420 Billion',
  '9.1%',
  'Continental, Bosch, Aptiv',
  420000000000,
  9.1,
  'Automotive electronics are driving vehicle intelligence, safety, and connectivity through advanced electronic systems.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Autonomous & Connected Vehicles (P4)
(
  5,
  'Autonomous & Connected Vehicles',
  'Autonomous and Connected Vehicles Market Research',
  'autonomous-connected-vehicles',
  'ACV',
  'Autonomous and Connected Vehicles Market Trends',
  'Autonomous and connected vehicles market research covering self-driving technology and vehicle connectivity.',
  '/images/sub-industries/autonomous.webp',
  'radar',
  '#6A1B9A',
  'Autonomous driving and connected vehicle technologies',
  'USD 300 Billion',
  '17.5%',
  'Waymo, Mobileye, NVIDIA',
  300000000000,
  17.5,
  'Autonomous and connected vehicle technologies are transforming transportation through AI, sensors, and vehicle-to-everything communication.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Commercial Vehicles (P5)
(
  5,
  'Commercial Vehicles',
  'Commercial Vehicles Market Research',
  'commercial-vehicles',
  'CV',
  'Commercial Vehicles Market Size & Outlook',
  'Commercial vehicles market research covering trucks, buses, and logistics vehicles.',
  '/images/sub-industries/commercial-vehicles.webp',
  'truck',
  '#5D4037',
  'Trucks, buses and logistics vehicles',
  'USD 900 Billion',
  '5.6%',
  'Daimler Truck, Volvo Group, Tata Motors',
  900000000000,
  5.6,
  'The commercial vehicles market supports global trade and logistics, driven by infrastructure development and e-commerce growth.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Mobility Services (P6)
(
  5,
  'Mobility Services',
  'Mobility Services Market Research',
  'mobility-services',
  'MOB',
  'Mobility Services Market Size & Forecast',
  'Mobility services market research covering ride-hailing, car sharing, and mobility-as-a-service.',
  '/images/sub-industries/mobility-services.webp',
  'map',
  '#00897B',
  'Ride-hailing, car sharing and MaaS',
  'USD 450 Billion',
  '14.2%',
  'Uber, Lyft, Grab',
  450000000000,
  14.2,
  'Mobility services are reshaping urban transportation by offering flexible, shared, and on-demand mobility solutions.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Automotive Aftermarket (P7)
(
  5,
  'Automotive Aftermarket',
  'Automotive Aftermarket Market Research',
  'automotive-aftermarket',
  'AM',
  'Automotive Aftermarket Market Size & Growth',
  'Automotive aftermarket market research covering replacement parts, accessories, and vehicle maintenance.',
  '/images/sub-industries/aftermarket.webp',
  'wrench',
  '#F9A825',
  'Replacement parts, accessories and maintenance',
  'USD 1.4 Trillion',
  '4.9%',
  'Bridgestone, Bosch, Continental',
  1400000000000,
  4.9,
  'The automotive aftermarket benefits from the growing global vehicle parc and increasing demand for maintenance and replacement parts.',
  7,
  b'1',
  '127.0.0.1',
  1
);



--------------------------------------------------
-- Industry : Chemicals & Materials --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Specialty Chemicals (P1)
(
  6,
  'Specialty Chemicals',
  'Specialty Chemicals Market Research',
  'specialty-chemicals',
  'SPEC',
  'Specialty Chemicals Market Size, Share & Forecast',
  'Specialty chemicals market research covering performance chemicals, additives, and formulated products.',
  '/images/sub-industries/specialty-chemicals.webp',
  'flask',
  '#00897B',
  'Performance chemicals, additives and formulations',
  'USD 850 Billion',
  '6.1%',
  'BASF, Dow, Evonik',
  850000000000,
  6.1,
  'Specialty chemicals are high-value, performance-driven products used across automotive, construction, electronics, and consumer goods industries.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Petrochemicals (P2)
(
  6,
  'Petrochemicals',
  'Petrochemicals Market Research',
  'petrochemicals',
  'PET',
  'Petrochemicals Market Size & Outlook',
  'Petrochemicals market research covering olefins, aromatics, and basic petrochemical products.',
  '/images/sub-industries/petrochemicals.webp',
  'droplet',
  '#455A64',
  'Olefins, aromatics and base petrochemicals',
  'USD 650 Billion',
  '4.3%',
  'SABIC, ExxonMobil Chemical, LyondellBasell',
  650000000000,
  4.3,
  'Petrochemicals form the foundation of plastics, synthetic materials, and industrial chemicals used globally.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Polymers & Plastics (P3)
(
  6,
  'Polymers & Plastics',
  'Polymers and Plastics Market Research',
  'polymers-plastics',
  'POLY',
  'Polymers and Plastics Market Trends & Forecast',
  'Polymers and plastics market research covering commodity and engineering plastics.',
  '/images/sub-industries/polymers.webp',
  'layers',
  '#1E88E5',
  'Commodity and engineering plastics',
  'USD 750 Billion',
  '5.2%',
  'Dow, BASF, Covestro',
  750000000000,
  5.2,
  'Polymers and plastics are widely used in packaging, automotive, construction, and consumer goods manufacturing.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Advanced Materials (P4)
(
  6,
  'Advanced Materials',
  'Advanced Materials Market Research',
  'advanced-materials',
  'ADV',
  'Advanced Materials Market Size & Forecast',
  'Advanced materials market research covering composites, nanomaterials, and high-performance materials.',
  '/images/sub-industries/advanced-materials.webp',
  'cube',
  '#6A1B9A',
  'Composites, nanomaterials and high-performance materials',
  'USD 300 Billion',
  '9.0%',
  '3M, DuPont, Toray',
  300000000000,
  9.0,
  'Advanced materials enable lightweighting, durability, and high performance across aerospace, electronics, and automotive applications.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Coatings, Adhesives & Sealants (P5)
(
  6,
  'Coatings, Adhesives & Sealants',
  'Coatings and Adhesives Market Research',
  'coatings-adhesives',
  'CAS',
  'Coatings and Adhesives Market Size & Growth',
  'Coatings and adhesives market research covering paints, coatings, adhesives, and sealants.',
  '/images/sub-industries/coatings.webp',
  'paintbrush',
  '#F9A825',
  'Paints, coatings, adhesives and sealants',
  'USD 280 Billion',
  '5.8%',
  'AkzoNobel, PPG Industries, Henkel',
  280000000000,
  5.8,
  'Coatings and adhesives are essential for surface protection, bonding, and durability across multiple industries.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Industrial Gases (P6)
(
  6,
  'Industrial Gases',
  'Industrial Gases Market Research',
  'industrial-gases',
  'GAS',
  'Industrial Gases Market Size & Outlook',
  'Industrial gases market research covering oxygen, nitrogen, hydrogen, and specialty gases.',
  '/images/sub-industries/industrial-gases.webp',
  'wind',
  '#3949AB',
  'Oxygen, nitrogen, hydrogen and specialty gases',
  'USD 120 Billion',
  '7.4%',
  'Linde, Air Liquide, Air Products',
  120000000000,
  7.4,
  'Industrial gases support manufacturing, healthcare, electronics, and energy industries worldwide.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Green & Sustainable Materials (P7)
(
  6,
  'Green & Sustainable Materials',
  'Sustainable Materials Market Research',
  'sustainable-materials',
  'GREEN',
  'Sustainable Materials Market Trends & Forecast',
  'Sustainable materials market research covering bio-based materials and recyclable materials.',
  '/images/sub-industries/sustainable-materials.webp',
  'leaf',
  '#2E7D32',
  'Bio-based, recyclable and sustainable materials',
  'USD 200 Billion',
  '10.8%',
  'NatureWorks, Novamont, Braskem',
  200000000000,
  10.8,
  'Green and sustainable materials are gaining traction due to environmental regulations and corporate sustainability initiatives.',
  7,
  b'1',
  '127.0.0.1',
  1
);


--------------------------------------------------
-- Industry : Consumer Goods & FMCG  --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Food Products (P1)
(
  7,
  'Food Products',
  'Food Products Market Research',
  'food-products',
  'FOOD',
  'Food Products Market Size, Share & Forecast',
  'Food products market research covering packaged foods, processed foods, and ready-to-eat products.',
  '/images/sub-industries/food-products.webp',
  'shopping-bag',
  '#6D4C41',
  'Packaged, processed and ready-to-eat foods',
  'USD 4.5 Trillion',
  '5.2%',
  'Nestle, Kraft Heinz, General Mills',
  4500000000000,
  5.2,
  'Food products represent the largest segment of the FMCG industry, driven by urbanization, convenience food demand, and changing consumer lifestyles.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Beverages (P2)
(
  7,
  'Beverages',
  'Beverages Market Research',
  'beverages',
  'BEV',
  'Beverages Market Size & Growth Outlook',
  'Beverages market research covering non-alcoholic and alcoholic beverages.',
  '/images/sub-industries/beverages.webp',
  'cup',
  '#3949AB',
  'Soft drinks, juices, alcoholic and functional beverages',
  'USD 1.8 Trillion',
  '4.9%',
  'PepsiCo, Coca-Cola, AB InBev',
  1800000000000,
  4.9,
  'The beverages market is shaped by brand competition, premiumization, health trends, and evolving consumer preferences.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Personal Care & Cosmetics (P3)
(
  7,
  'Personal Care & Cosmetics',
  'Personal Care Market Research',
  'personal-care-cosmetics',
  'PCC',
  'Personal Care and Cosmetics Market Forecast',
  'Personal care and cosmetics market research covering skincare, haircare, and beauty products.',
  '/images/sub-industries/personal-care.webp',
  'sparkles',
  '#8E24AA',
  'Skincare, haircare, cosmetics and hygiene products',
  'USD 650 Billion',
  '7.3%',
  'L’Oréal, Unilever, Procter & Gamble',
  650000000000,
  7.3,
  'Personal care and cosmetics benefit from rising disposable income, beauty awareness, and product innovation across global markets.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Household & Home Care (P4)
(
  7,
  'Household & Home Care',
  'Household and Home Care Market Research',
  'household-home-care',
  'HOME',
  'Household and Home Care Market Size & Outlook',
  'Household and home care market research covering cleaning products and home maintenance items.',
  '/images/sub-industries/household-care.webp',
  'home',
  '#455A64',
  'Cleaning products, detergents and home care items',
  'USD 300 Billion',
  '4.6%',
  'Reckitt, Henkel, SC Johnson',
  300000000000,
  4.6,
  'Household and home care products are essential consumer staples with steady demand driven by hygiene awareness and urban living.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Baby Care Products (P5)
(
  7,
  'Baby Care Products',
  'Baby Care Products Market Research',
  'baby-care-products',
  'BABY',
  'Baby Care Products Market Size & Forecast',
  'Baby care products market research covering infant nutrition, diapers, and baby hygiene products.',
  '/images/sub-industries/baby-care.webp',
  'baby',
  '#F9A825',
  'Infant food, diapers and baby hygiene products',
  'USD 110 Billion',
  '6.8%',
  'Johnson & Johnson, Kimberly-Clark, Danone',
  110000000000,
  6.8,
  'The baby care products market is driven by rising birth rates in emerging markets and increasing focus on infant health and hygiene.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Health & Wellness Products (P6)
(
  7,
  'Health & Wellness Products',
  'Health and Wellness Market Research',
  'health-wellness-products',
  'WELL',
  'Health and Wellness Products Market Trends',
  'Health and wellness market research covering functional foods, supplements, and nutrition products.',
  '/images/sub-industries/health-wellness.webp',
  'heart',
  '#2E7D32',
  'Functional foods, supplements and nutrition products',
  'USD 900 Billion',
  '8.9%',
  'Herbalife, Amway, Nestle Health Science',
  900000000000,
  8.9,
  'Health and wellness products are gaining popularity due to preventive healthcare trends and increasing consumer focus on nutrition.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Tobacco & Nicotine Products (P7)
(
  7,
  'Tobacco & Nicotine Products',
  'Tobacco and Nicotine Market Research',
  'tobacco-nicotine',
  'TOB',
  'Tobacco and Nicotine Products Market Outlook',
  'Tobacco and nicotine market research covering cigarettes, e-cigarettes, and smokeless products.',
  '/images/sub-industries/tobacco.webp',
  'smoke',
  '#6D4C41',
  'Cigarettes, e-cigarettes and nicotine products',
  'USD 850 Billion',
  '3.4%',
  'Philip Morris, BAT, Japan Tobacco',
  850000000000,
  3.4,
  'The tobacco and nicotine products market is shaped by regulation, harm-reduction strategies, and emerging alternatives such as vaping.',
  7,
  b'1',
  '127.0.0.1',
  1
);


--------------------------------------------------
-- Industry : Food & Beverage  --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Processed & Packaged Food (P1)
(
  8,
  'Processed & Packaged Food',
  'Processed Food Market Research',
  'processed-packaged-food',
  'PROC',
  'Processed and Packaged Food Market Size & Forecast',
  'Processed and packaged food market research covering ready meals, snacks, and convenience foods.',
  '/images/sub-industries/processed-food.webp',
  'shopping-bag',
  '#6D4C41',
  'Ready-to-eat, frozen and packaged foods',
  'USD 3.2 Trillion',
  '5.1%',
  'Nestle, Kraft Heinz, Conagra',
  3200000000000,
  5.1,
  'Processed and packaged food dominates global food consumption due to urbanization, convenience demand, and changing lifestyles.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Dairy Products (P2)
(
  8,
  'Dairy Products',
  'Dairy Products Market Research',
  'dairy-products',
  'DAIRY',
  'Dairy Products Market Size & Growth Outlook',
  'Dairy products market research covering milk, cheese, yogurt, butter, and dairy alternatives.',
  '/images/sub-industries/dairy.webp',
  'milk',
  '#3949AB',
  'Milk, cheese, yogurt and dairy products',
  'USD 720 Billion',
  '4.3%',
  'Danone, Lactalis, Nestle',
  720000000000,
  4.3,
  'The dairy products market is supported by nutritional demand, evolving diets, and growth of value-added dairy offerings.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Beverages (P3)
(
  8,
  'Beverages',
  'Beverages Market Research',
  'beverages',
  'BEV',
  'Beverages Market Size, Share & Forecast',
  'Beverages market research covering alcoholic, non-alcoholic, and functional beverages.',
  '/images/sub-industries/beverages.webp',
  'cup',
  '#1E88E5',
  'Soft drinks, alcoholic and functional beverages',
  'USD 1.8 Trillion',
  '4.9%',
  'Coca-Cola, PepsiCo, AB InBev',
  1800000000000,
  4.9,
  'The beverages market is driven by brand power, premiumization, health-focused drinks, and changing consumer preferences.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Bakery & Confectionery (P4)
(
  8,
  'Bakery & Confectionery',
  'Bakery and Confectionery Market Research',
  'bakery-confectionery',
  'BAKE',
  'Bakery and Confectionery Market Size & Outlook',
  'Bakery and confectionery market research covering bread, cakes, chocolates, and sugar-based products.',
  '/images/sub-industries/bakery.webp',
  'cake',
  '#8E24AA',
  'Bread, cakes, chocolates and confectionery',
  'USD 600 Billion',
  '4.7%',
  'Mondelez, Ferrero, Grupo Bimbo',
  600000000000,
  4.7,
  'Bakery and confectionery products benefit from strong consumer demand, indulgence trends, and global brand presence.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Meat, Poultry & Seafood (P5)
(
  8,
  'Meat, Poultry & Seafood',
  'Meat and Seafood Market Research',
  'meat-poultry-seafood',
  'MEAT',
  'Meat, Poultry and Seafood Market Trends',
  'Meat, poultry and seafood market research covering fresh, frozen, and processed animal protein.',
  '/images/sub-industries/meat.webp',
  'drumstick',
  '#455A64',
  'Animal protein, poultry and seafood products',
  'USD 1.5 Trillion',
  '4.2%',
  'Tyson Foods, JBS, Maruha Nichiro',
  1500000000000,
  4.2,
  'Meat, poultry, and seafood markets are driven by population growth, protein consumption, and cold-chain expansion.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Functional & Health Foods (P6)
(
  8,
  'Functional & Health Foods',
  'Functional Food Market Research',
  'functional-health-foods',
  'FUNC',
  'Functional and Health Foods Market Size & Forecast',
  'Functional and health foods market research covering fortified foods, probiotics, and nutrition-enhanced products.',
  '/images/sub-industries/functional-food.webp',
  'heart',
  '#2E7D32',
  'Fortified foods, probiotics and health foods',
  'USD 500 Billion',
  '8.6%',
  'Nestle Health Science, Danone, Yakult',
  500000000000,
  8.6,
  'Functional and health foods are growing rapidly due to preventive healthcare awareness and nutrition-focused lifestyles.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Plant-Based & Alternative Foods (P7)
(
  8,
  'Plant-Based & Alternative Foods',
  'Plant-Based Food Market Research',
  'plant-based-alternative-foods',
  'PLANT',
  'Plant-Based and Alternative Foods Market Outlook',
  'Plant-based and alternative food market research covering meat alternatives, dairy alternatives, and novel proteins.',
  '/images/sub-industries/plant-based.webp',
  'leaf',
  '#43A047',
  'Plant-based proteins and alternative foods',
  'USD 120 Billion',
  '12.9%',
  'Beyond Meat, Impossible Foods, Oatly',
  120000000000,
  12.9,
  'Plant-based and alternative foods are gaining traction due to sustainability concerns, health trends, and ethical consumption.',
  7,
  b'1',
  '127.0.0.1',
  1
);



--------------------------------------------------
-- Industry : Agriculture & Food  --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Crop Production & Farming (P1)
(
  9,
  'Crop Production & Farming',
  'Crop Production Market Research',
  'crop-production',
  'CROP',
  'Crop Production Market Size, Share & Forecast',
  'Crop production market research covering cereals, grains, oilseeds, fruits, and vegetables.',
  '/images/sub-industries/crop-production.webp',
  'leaf',
  '#2E7D32',
  'Cereals, grains, oilseeds, fruits and vegetables',
  'USD 3.5 Trillion',
  '4.6%',
  'Cargill, Archer Daniels Midland, Bunge',
  3500000000000,
  4.6,
  'Crop production is the foundation of the global food supply chain, driven by population growth, climate conditions, and agricultural productivity.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Agri-Tech & Smart Farming (P2)
(
  9,
  'Agri-Tech & Smart Farming',
  'Agri-Tech Market Research',
  'agri-tech',
  'AGT',
  'Agri-Tech and Smart Farming Market Outlook',
  'Agri-tech market research covering precision farming, farm automation, and digital agriculture.',
  '/images/sub-industries/agri-tech.webp',
  'cpu',
  '#3949AB',
  'Precision farming, farm automation and digital agriculture',
  'USD 250 Billion',
  '13.8%',
  'John Deere, Trimble, AGCO',
  250000000000,
  13.8,
  'Agri-tech and smart farming solutions improve crop yield, resource efficiency, and sustainability through data-driven agriculture.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Fertilizers & Agrochemicals (P3)
(
  9,
  'Fertilizers & Agrochemicals',
  'Fertilizers Market Research',
  'fertilizers-agrochemicals',
  'FERT',
  'Fertilizers and Agrochemicals Market Size & Forecast',
  'Fertilizers and agrochemicals market research covering nitrogen, phosphate, potash, and crop protection chemicals.',
  '/images/sub-industries/fertilizers.webp',
  'flask',
  '#00897B',
  'Fertilizers, pesticides and crop protection chemicals',
  'USD 300 Billion',
  '5.7%',
  'Nutrien, Yara, Bayer',
  300000000000,
  5.7,
  'Fertilizers and agrochemicals play a critical role in improving agricultural productivity and food security worldwide.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Livestock & Animal Farming (P4)
(
  9,
  'Livestock & Animal Farming',
  'Livestock Market Research',
  'livestock-animal-farming',
  'LIVE',
  'Livestock and Animal Farming Market Outlook',
  'Livestock market research covering dairy farming, poultry, cattle, and animal husbandry.',
  '/images/sub-industries/livestock.webp',
  'cow',
  '#6D4C41',
  'Dairy, poultry, cattle and animal farming',
  'USD 1.4 Trillion',
  '4.3%',
  'Tyson Foods, JBS, Zoetis',
  1400000000000,
  4.3,
  'Livestock and animal farming support global protein demand and are closely linked to feed, veterinary, and animal health markets.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Seeds & Plant Breeding (P5)
(
  9,
  'Seeds & Plant Breeding',
  'Seeds Market Research',
  'seeds-plant-breeding',
  'SEED',
  'Seeds and Plant Breeding Market Trends',
  'Seeds market research covering hybrid seeds, GM seeds, and plant breeding technologies.',
  '/images/sub-industries/seeds.webp',
  'sprout',
  '#43A047',
  'Hybrid seeds, GM seeds and plant breeding',
  'USD 90 Billion',
  '6.9%',
  'Bayer CropScience, Corteva, Syngenta',
  90000000000,
  6.9,
  'Seeds and plant breeding technologies improve crop yield, disease resistance, and climate resilience.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Agricultural Equipment & Machinery (P6)
(
  9,
  'Agricultural Equipment & Machinery',
  'Agricultural Equipment Market Research',
  'agricultural-equipment',
  'EQUIP',
  'Agricultural Equipment and Machinery Market Size',
  'Agricultural equipment market research covering tractors, harvesters, and farming machinery.',
  '/images/sub-industries/agri-equipment.webp',
  'tractor',
  '#455A64',
  'Tractors, harvesters and agricultural machinery',
  'USD 200 Billion',
  '5.4%',
  'John Deere, CNH Industrial, Kubota',
  200000000000,
  5.4,
  'Agricultural machinery enhances farm productivity and efficiency, supporting large-scale and mechanized farming.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Organic & Sustainable Agriculture (P7)
(
  9,
  'Organic & Sustainable Agriculture',
  'Organic Agriculture Market Research',
  'organic-sustainable-agriculture',
  'ORG',
  'Organic and Sustainable Agriculture Market Outlook',
  'Organic and sustainable agriculture market research covering organic farming and eco-friendly practices.',
  '/images/sub-industries/organic.webp',
  'leaf',
  '#2E7D32',
  'Organic farming and sustainable agricultural practices',
  'USD 180 Billion',
  '10.5%',
  'Danone, Whole Foods Market, Earthbound Farm',
  180000000000,
  10.5,
  'Organic and sustainable agriculture is gaining momentum due to environmental concerns, health awareness, and regulatory support.',
  7,
  b'1',
  '127.0.0.1',
  1
);


--------------------------------------------------
-- Industry : BFSI  --
--------------------------------------------------

INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Banking (P1)
(
  10,
  'Banking',
  'Banking Market Research',
  'banking',
  'BANK',
  'Banking Market Size, Share & Forecast',
  'Banking market research covering retail banking, corporate banking, and digital banking services.',
  '/images/sub-industries/banking.webp',
  'bank',
  '#283593',
  'Retail, corporate and digital banking services',
  'USD 9.5 Trillion',
  '5.4%',
  'JPMorgan Chase, HSBC, ICICI Bank',
  9500000000000,
  5.4,
  'The banking sector is the core of the global financial system, driven by credit demand, digital transformation, and regulatory compliance.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Insurance (P2)
(
  10,
  'Insurance',
  'Insurance Market Research',
  'insurance',
  'INS',
  'Insurance Market Size & Growth Outlook',
  'Insurance market research covering life insurance, health insurance, and property & casualty insurance.',
  '/images/sub-industries/insurance.webp',
  'shield',
  '#1565C0',
  'Life, health and general insurance',
  'USD 7.0 Trillion',
  '5.2%',
  'Allianz, AXA, Prudential',
  7000000000000,
  5.2,
  'The insurance industry manages risk across individuals and enterprises, with demand driven by economic growth and regulatory mandates.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Financial Technology (FinTech) (P3)
(
  10,
  'Financial Technology (FinTech)',
  'FinTech Market Research',
  'fintech',
  'FIN',
  'FinTech Market Size, Trends & Forecast',
  'FinTech market research covering digital payments, lending platforms, neobanks, and financial software.',
  '/images/sub-industries/fintech.webp',
  'credit-card',
  '#00897B',
  'Digital payments, lending platforms and neobanks',
  'USD 500 Billion',
  '18.7%',
  'Stripe, PayPal, Ant Group',
  500000000000,
  18.7,
  'FinTech is transforming traditional financial services through digital platforms, automation, and customer-centric innovation.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Payments & Money Transfer (P4)
(
  10,
  'Payments & Money Transfer',
  'Payments Market Research',
  'payments-money-transfer',
  'PAY',
  'Payments and Money Transfer Market Outlook',
  'Payments market research covering digital payments, remittances, and payment gateways.',
  '/images/sub-industries/payments.webp',
  'repeat',
  '#3949AB',
  'Digital payments, remittances and gateways',
  'USD 2.3 Trillion',
  '9.5%',
  'Visa, Mastercard, Western Union',
  2300000000000,
  9.5,
  'Payments and money transfer services are expanding rapidly due to cashless adoption and cross-border transactions.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Capital Markets & Investment Services (P5)
(
  10,
  'Capital Markets & Investment Services',
  'Capital Markets Market Research',
  'capital-markets',
  'CAP',
  'Capital Markets and Investment Services Market Size',
  'Capital markets market research covering equities, bonds, asset management, and trading platforms.',
  '/images/sub-industries/capital-markets.webp',
  'trending-up',
  '#6A1B9A',
  'Equities, bonds, asset management and trading',
  'USD 1.8 Trillion',
  '6.1%',
  'BlackRock, Goldman Sachs, Morgan Stanley',
  1800000000000,
  6.1,
  'Capital markets support investment, wealth creation, and liquidity across global financial systems.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Wealth Management & Private Banking (P6)
(
  10,
  'Wealth Management & Private Banking',
  'Wealth Management Market Research',
  'wealth-management',
  'WM',
  'Wealth Management and Private Banking Market Outlook',
  'Wealth management market research covering private banking, advisory services, and HNWI solutions.',
  '/images/sub-industries/wealth-management.webp',
  'briefcase',
  '#455A64',
  'Private banking, advisory and HNWI services',
  'USD 900 Billion',
  '7.3%',
  'UBS, Credit Suisse, Morgan Stanley',
  900000000000,
  7.3,
  'Wealth management services are driven by rising high-net-worth individuals and demand for personalized financial solutions.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Risk Management & Compliance (P7)
(
  10,
  'Risk Management & Compliance',
  'Risk Management Market Research',
  'risk-compliance',
  'RISK',
  'Risk Management and Compliance Market Trends',
  'Risk management and compliance market research covering regulatory technology and financial risk solutions.',
  '/images/sub-industries/risk.webp',
  'alert-triangle',
  '#D32F2F',
  'Financial risk, compliance and regtech solutions',
  'USD 180 Billion',
  '11.4%',
  'FIS, Refinitiv, Moody’s Analytics',
  180000000000,
  11.4,
  'Risk management and compliance solutions help financial institutions manage regulatory pressure and operational risk.',
  7,
  b'1',
  '127.0.0.1',
  1
);


--------------------------------------------------
-- Industry : Aerospace & Defense  --
--------------------------------------------------


INSERT INTO sub_industries_master
(
  industry_id,
  Name,
  Rephrased_Name,
  Path,
  Initial,
  seo_title,
  seo_description,
  Image_Path,
  Icon,
  Color,
  description,
  marketSize,
  growthRate,
  topPlayers,
  market_size_value,
  growth_rate_value,
  overview,
  priority,
  IsActive,
  Ip,
  CreateBY
)
VALUES

-- 1️⃣ Military Aircraft & Aviation (P1)
(
  11,
  'Military Aircraft & Aviation',
  'Military Aviation Market Research',
  'military-aviation',
  'MIL',
  'Military Aircraft and Aviation Market Size & Forecast',
  'Military aviation market research covering fighter jets, transport aircraft, and military aviation systems.',
  '/images/sub-industries/military-aviation.webp',
  'plane',
  '#455A64',
  'Fighter jets, transport aircraft and military aviation',
  'USD 450 Billion',
  '4.2%',
  'Lockheed Martin, Boeing Defense, Airbus Defence',
  450000000000,
  4.2,
  'Military aviation remains a core defense spending area, driven by fleet modernization, geopolitical tensions, and air superiority programs.',
  1,
  b'1',
  '127.0.0.1',
  1
),

-- 2️⃣ Defense Systems & Weapons (P2)
(
  11,
  'Defense Systems & Weapons',
  'Defense Systems Market Research',
  'defense-systems',
  'DEF',
  'Defense Systems and Weapons Market Outlook',
  'Defense systems market research covering missiles, weapons systems, radar, and defense electronics.',
  '/images/sub-industries/defense-systems.webp',
  'target',
  '#D32F2F',
  'Weapons, missiles, radar and defense systems',
  'USD 600 Billion',
  '5.1%',
  'Raytheon, Northrop Grumman, BAE Systems',
  600000000000,
  5.1,
  'Defense systems and weapons markets are driven by national security priorities and continuous defense modernization programs.',
  2,
  b'1',
  '127.0.0.1',
  1
),

-- 3️⃣ Space & Satellite Systems (P3)
(
  11,
  'Space & Satellite Systems',
  'Space and Satellite Market Research',
  'space-satellite',
  'SPACE',
  'Space and Satellite Systems Market Size & Growth',
  'Space and satellite market research covering launch services, satellites, and space infrastructure.',
  '/images/sub-industries/space.webp',
  'satellite',
  '#1E88E5',
  'Satellites, launch vehicles and space infrastructure',
  'USD 550 Billion',
  '7.8%',
  'SpaceX, Blue Origin, Thales Alenia Space',
  550000000000,
  7.8,
  'Space and satellite systems support communication, navigation, defense intelligence, and commercial space exploration.',
  3,
  b'1',
  '127.0.0.1',
  1
),

-- 4️⃣ Unmanned Systems & Drones (P4)
(
  11,
  'Unmanned Systems & Drones',
  'Drone and UAV Market Research',
  'unmanned-systems-drones',
  'UAV',
  'Unmanned Systems and Drones Market Trends',
  'Unmanned systems market research covering UAVs, UGVs, and autonomous defense platforms.',
  '/images/sub-industries/drones.webp',
  'drone',
  '#6A1B9A',
  'UAVs, UGVs and autonomous defense platforms',
  'USD 120 Billion',
  '12.6%',
  'General Atomics, DJI, AeroVironment',
  120000000000,
  12.6,
  'Unmanned systems and drones are increasingly adopted for surveillance, reconnaissance, and combat operations.',
  4,
  b'1',
  '127.0.0.1',
  1
),

-- 5️⃣ Naval Systems & Shipbuilding (P5)
(
  11,
  'Naval Systems & Shipbuilding',
  'Naval Systems Market Research',
  'naval-systems',
  'NAV',
  'Naval Systems and Shipbuilding Market Outlook',
  'Naval systems market research covering warships, submarines, and naval defense platforms.',
  '/images/sub-industries/naval.webp',
  'anchor',
  '#283593',
  'Warships, submarines and naval defense systems',
  'USD 300 Billion',
  '4.0%',
  'Huntington Ingalls, Naval Group, BAE Systems',
  300000000000,
  4.0,
  'Naval systems support maritime security and defense, with long-term procurement contracts and modernization programs.',
  5,
  b'1',
  '127.0.0.1',
  1
),

-- 6️⃣ Aerospace Components & MRO (P6)
(
  11,
  'Aerospace Components & MRO',
  'Aerospace Components Market Research',
  'aerospace-components-mro',
  'MRO',
  'Aerospace Components and MRO Market Size',
  'Aerospace components and MRO market research covering aircraft parts, maintenance, and repair services.',
  '/images/sub-industries/aerospace-components.webp',
  'settings',
  '#00897B',
  'Aircraft components, MRO and aftermarket services',
  'USD 380 Billion',
  '5.6%',
  'Safran, Honeywell Aerospace, RTX',
  380000000000,
  5.6,
  'Aerospace components and MRO services ensure aircraft safety, reliability, and lifecycle management.',
  6,
  b'1',
  '127.0.0.1',
  1
),

-- 7️⃣ Cybersecurity & Defense IT (P7)
(
  11,
  'Cybersecurity & Defense IT',
  'Defense IT Market Research',
  'defense-it-cybersecurity',
  'CYB',
  'Cybersecurity and Defense IT Market Trends',
  'Defense IT and cybersecurity market research covering cyber defense, C4ISR, and secure communication.',
  '/images/sub-industries/defense-it.webp',
  'shield',
  '#C62828',
  'Cyber defense, C4ISR and secure communication',
  'USD 200 Billion',
  '9.8%',
  'Palantir, Lockheed Martin, Booz Allen',
  200000000000,
  9.8,
  'Cybersecurity and defense IT systems are critical for protecting national security infrastructure and military networks.',
  7,
  b'1',
  '127.0.0.1',
  1
);
